In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential   # MAINTAINS THE SEQUENCE OF THE MODEL.
from tensorflow.keras.layers import Dense   # 1D LAYER.
from tensorflow.keras.layers import Dropout,BatchNormalization  # PREVENTS OVERFITTING.
from tensorflow.keras.callbacks import EarlyStopping  # PREVENTS OVERFITTING.
from sklearn.preprocessing import LabelEncoder

In [ ]:
#                            ANN (Artificail Nural Networks)

In [40]:
df=pd.read_csv(r'C:\Users\amank\Downloads\DEEP LEARNING ANN\Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
#                                 DROP USELESS COLUMNS

In [41]:
df.drop(columns=['RowNumber','CustomerId','Surname','Geography'],inplace=True)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
#                      HANDLING CATEGORICAL DATA

In [42]:
label=LabelEncoder()

In [43]:
df['encoded_gender']=label.fit_transform(df['Gender'])

In [44]:
df.drop(columns=['Gender'],inplace=True)

In [45]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,encoded_gender
0,619,42,2,0.00,1,1,1,101348.88,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0

In [46]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [56]:
x.shape

(10000, 9)

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [48]:
model=Sequential()

In [49]:
model.add(Dense(3, activation='relu', input_dim=9))  # LAYER ONE
model.add(Dense(3, activation='relu'))               # LAYER TWO
model.add(Dense(1, activation='sigmoid'))            # OUTPUT LAYER

c:\Users\amank\Downloads\DEEP LEARNING ANN\.Deelearn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
#                       TO CHECK THE TRAIN-ABLE PARAMETERS

In [50]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 3)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 3)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 46 (184.00 B)

 Trainable params: 46 (184.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#                  COMPILATION OF MODEL

In [52]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [ ]:
#                            FIT THE MODEL

In [54]:
model.fit(x_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.4952 - loss: 4.8405
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7887 - loss: 0.6309
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7829 - loss: 0.6122
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.7849 - loss: 0.5804
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7846 - loss: 0.5665
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7809 - loss: 0.5640
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.7883 - loss: 0.5505
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.7870 - loss: 0.5342
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.7793 - loss: 0.5469
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.7835 - loss: 0.5406

In [55]:
model.get_weights()

[array([[ 0.74261254,  0.13580613, -0.0359703 ],
        [-0.09499235, -0.20650451,  0.08362638],
        [ 0.03862496, -0.5635715 , -0.11248013],
        [ 0.2775364 , -0.254933  ,  0.32140294],
        [ 0.48634428,  0.0281406 ,  0.66519815],
        [ 0.6172131 , -0.11270541,  0.30685645],
        [ 0.340223  , -0.6012455 , -0.27962285],
        [ 0.28072494,  0.23857756, -0.44155014],
        [-0.11184366, -0.6941586 ,  0.00942098]], dtype=float32),
 array([ 0.07349154, -0.14490154,  0.07003773], dtype=float32),
 array([[ 0.05374196, -0.18506037, -0.9682596 ],
        [-0.11940861,  0.21067908, -0.4763744 ],
        [-0.7941009 , -0.43302393, -0.9446044 ]], dtype=float32),
 array([-0.13528888, -0.17668672,  0.        ], dtype=float32),
 array([[ 4.5742054e-04],
        [-1.2058821e-01],
        [ 6.8682098e-01]], dtype=float32),
 array([-1.2166977], dtype=float32)]