In [5]:
# loading libaries
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential  # smaintains the sequence of the model 
from tensorflow.keras.layers import Dense  # 1d layer
from tensorflow.keras.layers import Dropout,BatchNormalization # tpo prevent overfitting 
from tensorflow.keras.callbacks import EarlyStopping  # to prevent ovrfitting

In [6]:
# data loading 
df=pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
# drop useless columns
df.drop(columns=["RowNumber","CustomerId","Surname","Geography"],inplace=True)

In [11]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
# handle catgorical data 

df["Gender"]=df["Gender"].map({"Male":1,"Female":0})

In [13]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,42,2,0.00,1,1,1,101348.88,1
1,608,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,39,1,0.00,2,0,0,93826.63,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0

In [16]:
# feature selection 
x=df.drop(columns=["Exited"])
y=df["Exited"]
x.shape

(10000, 9)

In [15]:
# data spliting 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
df.shape

(10000, 10)

In [28]:
model.get_weights()

[array([[-5.28666899e-02, -2.24230319e-01, -2.56767869e-01,
          1.50593147e-01, -1.86562434e-01, -2.69868731e-01,
          1.28696561e-01,  2.11317003e-01, -2.09894717e-01,
          1.41420990e-01,  2.63127565e-01, -1.20489903e-01,
          2.55852133e-01,  1.38620362e-01, -1.21388882e-01,
         -3.10260117e-01, -1.67952433e-01,  2.03006655e-01,
         -1.11066073e-01, -2.15181038e-02, -2.43198350e-01,
         -2.13000387e-01,  2.02583540e-02, -1.95980504e-01,
          8.77336115e-02, -3.12433004e-01, -7.60007873e-02,
          2.07909822e-01,  9.13628712e-02, -1.19817041e-01,
         -1.36161121e-02,  2.25948244e-01, -8.32070336e-02,
          2.67083675e-01,  7.56262317e-02, -2.36004546e-01,
          2.24797521e-02, -8.14204663e-02,  1.12533635e-02,
         -2.56002486e-01, -1.03531703e-01, -3.77185340e-03,
         -2.24308297e-01,  1.91137791e-01, -2.23494723e-01,
          7.74159655e-02,  1.42508939e-01, -2.35928729e-01,
         -2.91166119e-02, -6.00990653e-02,  1.72671720e-01,
         -1.18015051e-01, -1.16783008e-01,  9.95293707e-02,
         -5.42224646e-02,  1.52827919e-01,  2.22750902e-01,
          3.43488976e-02, -2.38975838e-01, -2.14486212e-01,
          1.48961052e-01,  8.85497108e-02,  2.59647787e-01,
         -3.34162116e-01],
        [ 2.75764585e-01,  2.86310226e-01,  2.20561683e-01,
          2.90481657e-01,  2.50611991e-01,  1.34021461e-01,
         -2.23695070e-01, -2.93933570e-01, -5.17894804e-01,
         -2.21449479e-01, -3.18258069e-02,  3.63296658e-01,
          1.07464716e-01,  2.95319378e-01,  1.88848883e-01,
          1.62399277e-01,  4.74198341e-01,  2.42923230e-01,
          4.05588716e-01, -4.56290394e-02, -2.70275772e-01,
         -3.78499150e-01, -4.37975347e-01,  1.82289202e-02,
          1.12903818e-01, -4.42698926e-01, -4.21372354e-01,
         -3.51651937e-01,  1.20241963e-03, -1.14548355e-01,
          6.96309805e-02, -6.48865029e-02,  2.92501580e-02,
         -1.63655430e-01, -3.36115062e-02, -1.66131686e-02,
         -2.09264219e-01, -2.25507513e-01,  1.86232850e-01,
          2.64504105e-01,  4.59681958e-01, -4.25694674e-01,
          9.23476070e-02, -3.40743959e-01, -7.54843131e-02,
          2.83745557e-01, -4.97177243e-01, -7.99583420e-02,
         -1.12539366e-01,  2.03933954e-01,  1.34629130e-01,
         -3.27131242e-01, -2.98905462e-01, -2.72025496e-01,
          6.09741211e-02,  3.78362864e-01,  2.59972066e-01,
         -9.67517197e-02, -4.51293677e-01, -2.26287603e-01,
          9.78696644e-02,  1.90961570e-01,  2.39002466e-01,
         -3.36916387e-01],
        [-2.46384386e-02,  2.30359435e-02,  7.36938370e-03,
         -8.48154351e-03, -2.13107467e-01, -1.53783783e-01,
          3.14189941e-01, -2.06853017e-01,  1.31847113e-01,
          1.50471702e-01,  2.62878507e-01, -2.45318174e-01,
         -1.29600763e-01,  5.08741029e-02, -2.25562930e-01,
          1.84773937e-01, -5.37512362e-01, -6.50678482e-03,
         -2.80307811e-02,  9.77808759e-02, -7.67211467e-02,
         -2.59436131e-01,  4.31029081e-01, -1.08784810e-01,
         -4.58376408e-01,  7.67223909e-02,  3.96347672e-01,
          2.83733159e-01, -4.12913859e-02, -1.91658154e-01,
         -1.54880598e-01,  3.58365327e-01,  8.90162066e-02,
          2.19420463e-01, -1.49581516e-02,  2.50023931e-01,
         -3.77011478e-01,  2.64675945e-01, -5.48871458e-02,
          2.56467134e-01, -4.74911869e-01,  6.01777516e-04,
         -3.79177511e-01,  1.54791892e-01, -9.75881666e-02,
         -3.48906904e-01,  3.83219719e-02,  3.76267894e-03,
          1.61312118e-01,  3.16127539e-02, -4.67426553e-02,
          2.68506527e-01,  2.83478796e-01,  3.13035965e-01,
          2.09024325e-01, -9.50904563e-02, -8.50063115e-02,
         -2.42935419e-01,  2.37636372e-01,  1.12121165e-01,
         -1.13950096e-01, -3.03244710e-01, -3.56077671e-01,
         -7.78072551e-02],
        [ 5.08717485e-02, -2.84600347e-01,  1.02665182e-02,
         -2.06203431e-01,  9.66403782e-02, -1.88689843e-01,
          1.13748841e-01,  9.11453664e-02,  1.76062092e-01,
          3.42999734e-02, -1.19606322e-02,  2.53827214e-01,
         -1.59390718e-01, -3.47209871e-02, -9.63940173e-02,
          1.84440717e-01,  2.39464954e-01,  7.92258903e-02,
          8.92633796e-02, -2.39370335e-02,  2.66547203e-02,
         -1.69210061e-01,  1.32799074e-01, -2.39757746e-02,
          5.34335002e-02, -1.41108975e-01, -1.61050245e-01,
         -1.98724046e-01, -1.09192334e-01,  7.67947584e-02,
         -4.47253138e-02, -2.94395775e-01,  1.97957307e-01,
         -1.67480260e-01,  1.89475268e-01, -1.73425823e-01,
         -3.39537203e-01, -6.21431693e-02,  7.61471987e-02,
         -1.70907319e-01,  6.07396290e-03,  4.46594916e-02,
         -1.29061550e-01,  1.76666334e-01, -1.56016290e-01,
         -2.82089353e-01, -2.03936353e-01, -1.22461714e-01,
          6.40661716e-02, -3.97539437e-02,  4.80525829e-02,
          1.31832466e-01, -2.20476702e-01,  1.75835088e-01,
          2.80461848e-01, -1.32431507e-01,  3.25727612e-01,
          4.62723225e-02, -1.62088722e-01,  2.65743166e-01,
         -2.19313025e-01, -3.24015468e-02,  1.67447887e-02,
          2.77593553e-01],
        [-1.05752945e-01, -3.41722369e-03, -2.66326759e-02,
         -6.43041059e-02, -1.51178062e-01,  2.20360681e-01,
          2.56175190e-01, -4.03020531e-02,  2.56846976e-02,
          2.11962670e-01, -7.60429725e-02,  2.35766456e-01,
          1.51900500e-01, -2.47016549e-01, -1.72242656e-01,
         -1.37304202e-01,  1.02099761e-01,  5.22932224e-02,
          1.32924721e-01, -2.19406351e-01, -1.99541003e-01,
         -3.00221860e-01,  2.27196813e-01,  2.36767903e-01,
          2.70994991e-01,  4.21593376e-02,  2.31922343e-01,
          1.92844957e-01,  2.61222813e-02,  3.75396088e-02,
         -5.04122004e-02,  1.52397916e-01, -5.43158837e-02,
         -6.91059381e-02,  1.75310314e-01, -2.21905529e-01,
         -1.29060090e-01,  4.49960008e-02, -1.61489516e-01,
         -2.49011457e-01,  2.74422050e-01,  2.23275691e-01,
         -4.68950085e-02,  1.21464152e-02,  2.14770883e-01,
          8.22594762e-03,  2.43677169e-01,  1.66842043e-01,
          1.93080962e-01, -1.09491721e-01, -1.27437264e-01,
          1.84193879e-01,  1.97469056e-01,  2.04592813e-02,
          5.82026578e-02,  2.07267880e-01, -1.44779176e-01,
         -3.10834032e-03,  7.13990256e-02, -9.89868343e-02,
          1.52655691e-01,  2.15663418e-01,  1.22117482e-01,
          9.93854478e-02],
        [-1.99409157e-01,  3.88599634e-02, -1.24421477e-01,
          2.89113402e-01,  3.10376287e-02, -9.17859077e-02,
          3.21236938e-01,  2.35144466e-01,  2.77806725e-02,
          1.61699384e-01,  2.74743468e-01, -1.53205886e-01,
          6.04855781e-03,  2.48838440e-01, -2.78982252e-01,
         -2.73317099e-01, -3.10566872e-01,  6.54441193e-02,
          2.19594002e-01, -2.45475948e-01,  1.32354736e-01,
         -1.42168552e-01,  6.53558001e-02, -2.93422073e-01,
          1.04647674e-01,  1.71061046e-02,  1.43143773e-01,
          1.26369745e-01,  4.79323454e-02, -1.60965264e-01,
         -1.64033145e-01, -8.39387998e-02, -1.58723235e-01,
          1.06418468e-01,  3.23673412e-02,  2.37024814e-01,
         -1.49632215e-01,  1.98492080e-01, -2.11292475e-01,
         -7.74361938e-02,  2.68350281e-02, -1.65059432e-01,
          2.36623183e-01, -1.42240942e-01,  4.22093533e-02,
          1.49778262e-01,  3.28332275e-01, -2.11417139e-01,
         -2.75207996e-01, -4.46939170e-02, -2.32469156e-01,
          1.51419029e-01, -1.22626573e-01, -1.30506471e-01,
         -2.16127291e-01, -1.45253256e-01, -2.91130960e-01,
         -1.58516437e-01,  1.13466688e-01, -2.74931878e-01,
          1.96489483e-01,  3.99206541e-02, -6.58968315e-02,
          1.57778785e-01],
        [-2.64871508e-01,  1.11153245e-01, -1.90947533e-01,
          3.76737341e-02,  6.44294024e-02,  1.55795321e-01,
          6.45561963e-02, -3.04676127e-02,  1.75801784e-01,
         -2.72374868e-01,  4.90923896e-02, -1.66634709e-01,
         -1.68058891e-02,  7.81658441e-02,  2.48963743e-01,
          9.28107202e-02,  1.68419760e-02, -2.18834683e-01,
         -1.20303124e-01,  2.04166085e-01,  1.92579299e-01,
          3.79955769e-02, -8.93446580e-02, -1.35567561e-01,
          1.70007348e-01, -1.32973596e-01, -1.64998755e-01,
         -1.62650615e-01, -1.84334025e-01,  5.33904061e-02,
          9.19071883e-02, -9.33965743e-02, -1.41810581e-01,
         -2.90187746e-01, -1.79710776e-01, -6.41506352e-03,
          1.16079241e-01, -3.03092331e-01,  1.88427299e-01,
          2.48575658e-01, -5.98895922e-02,  2.22012505e-01,
          1.39025912e-01, -1.42570928e-01,  1.81273825e-03,
         -2.26983547e-01,  1.95271537e-01, -2.26238489e-01,
          4.19654064e-02, -2.23231152e-01,  1.97218969e-01,
          7.35909715e-02, -1.12950958e-01,  5.22295665e-03,
          3.15773755e-01,  1.87968418e-01, -4.39399667e-02,
          1.69499069e-01, -1.62882045e-01, -2.17817083e-01,
         -5.14717363e-02,  7.70404115e-02, -1.62934139e-01,
         -1.66437134e-01],
        [ 5.89430511e-01, -2.83153236e-01,  1.92739293e-01,
          1.69606715e-01,  2.15176791e-01,  5.49981356e-01,
         -2.44588390e-01, -8.01951345e-03, -2.79416829e-01,
         -5.04560828e-01, -8.58606100e-02,  7.07476795e-01,
          5.87435782e-01,  2.43430063e-01, -1.68119282e-01,
         -2.05318838e-01,  5.88102102e-01,  8.28382075e-02,
          2.26660464e-02,  1.12095978e-02,  1.36338383e-01,
          8.15916136e-02, -1.29168227e-01,  4.71571743e-01,
          1.88234612e-01, -5.25695682e-01, -2.47632325e-01,
         -6.90593719e-01, -9.45924595e-02, -1.98795095e-01,
         -5.23203254e-01, -1.28080741e-01,  5.48002310e-02,
          2.65925497e-01, -2.96516806e-01, -5.68916917e-01,
         -2.44282797e-01, -5.06405294e-01,  9.87751707e-02,
          5.46242297e-02,  5.20993054e-01, -5.11239052e-01,
          3.26162606e-01, -5.39752543e-02,  1.82222277e-01,
         -8.43596086e-02, -4.27995801e-01, -7.15625525e-01,
         -1.91059679e-01, -1.21948078e-01,  4.30836409e-01,
         -2.77657747e-01, -3.15989166e-01, -3.54551017e-01,
         -5.01065282e-03,  5.87323666e-01, -5.03547728e-01,
          9.11291614e-02, -6.62553132e-01,  1.20463520e-01,
          6.68311596e-01,  2.99502581e-01,  5.93910873e-01,
         -1.96017906e-01],
        [ 1.42494097e-01, -2.06849307e-01,  1.44432262e-01,
          1.20756529e-01, -1.37378871e-02,  6.84232190e-02,
         -1.17595889e-01, -1.69348314e-01,  2.18191847e-01,
          2.03012452e-01, -3.23370588e-03, -1.93030700e-01,
          2.22164080e-01,  2.88937837e-01, -3.70249748e-02,
          2.74665793e-03,  1.53162777e-01, -2.00920895e-01,
          1.27108082e-01, -7.29076862e-02, -1.82832360e-01,
          3.52573730e-02,  1.52072951e-01, -2.17178330e-01,
          1.04994342e-01, -1.72446206e-01, -1.01163983e-01,
          1.91419691e-01, -2.98366547e-01, -5.64673506e-02,
          1.66990474e-01,  2.03879759e-01,  5.14057651e-02,
         -1.69591516e-01, -2.66737580e-01,  2.49009401e-01,
         -7.37521390e-04, -6.60497174e-02, -1.06595591e-01,
         -2.44766280e-01,  1.55283675e-01,  1.18033320e-01,
          3.12398020e-02, -1.50762737e-01, -4.83845100e-02,
         -4.41200621e-02, -5.91837987e-02,  1.75691769e-01,
          1.35578498e-01, -2.84445852e-01, -1.62435606e-01,
         -8.10554251e-02, -2.58473843e-01, -2.14814901e-01,
          1.72813982e-01, -9.31736007e-02, -1.53809503e-01,
         -7.82250166e-02,  4.49178480e-02, -2.77004927e-01,
          1.14748605e-01,  9.04893726e-02, -1.23026244e-01,
         -5.54225594e-02]], dtype=float32),
 array([-0.02041368,  0.        , -0.03449324, -0.02926462,  0.        ,
        -0.00349993, -0.05124485, -0.05483104,  0.00020727, -0.02801322,
         0.08017817,  0.01401368, -0.04010796, -0.03863262,  0.        ,
        -0.03145051, -0.04439213, -0.02140885, -0.03112403, -0.02220856,
         0.        , -0.06672577, -0.01575146,  0.02477776,  0.02474934,
        -0.04897057, -0.00056952, -0.00132102, -0.02085813, -0.04406267,
        -0.0512993 , -0.01337036, -0.03890232, -0.00212592, -0.05575584,
        -0.0207968 , -0.10711517, -0.05216957, -0.02161996,  0.        ,
         0.00821643, -0.02906356, -0.00846378, -0.07696591, -0.0288847 ,
        -0.0035076 , -0.00866114,  0.00655135, -0.00802802,  0.        ,
         0.00075297, -0.05880081, -0.06398556, -0.0013306 ,  0.02933021,
         0.01156386,  0.02049891, -0.00746166, -0.00040535,  0.        ,
        -0.00388957, -0.00414677, -0.00585063, -0.05663627], dtype=float32),
 array([[-0.0096899 ,  0.04701863, -0.01129255, ..., -0.01044422,
         -0.17140932,  0.16309838],
        [-0.07584581,  0.07692103,  0.04699577, ..., -0.15569276,
          0.06006624, -0.03736003],
        [ 0.08668695,  0.04204176, -0.02912854, ...,  0.08009186,
         -0.08906702, -0.03689883],
        ...,
        [ 0.01683098, -0.04603089,  0.08858036, ...,  0.03471394,
          0.1230668 ,  0.16569594],
        [-0.2172022 , -0.1951064 , -0.12086038, ...,  0.20640594,
         -0.1054542 ,  0.19809602],
        [-0.12305924, -0.16826642,  0.1939989 , ..., -0.02050025,
         -0.01958251, -0.03823868]], shape=(64, 64), dtype=float32),
 array([ 5.0290575e-05,  0.0000000e+00, -4.6020900e-03, -3.0716075e-02,
         4.5124341e-02, -2.0099677e-02,  2.6653770e-03, -2.4834046e-02,
         3.8838661e-03, -4.1082680e-02, -1.9617356e-02,  2.8383350e-03,
         0.0000000e+00,  3.0497257e-02, -6.8175964e-02,  0.0000000e+00,
        -2.3368930e-02, -2.2009874e-02,  0.0000000e+00, -2.1548860e-02,
        -2.1291655e-02, -4.0757782e-03, -2.8426932e-05,  3.8029300e-03,
         0.0000000e+00,  1.7735688e-02,  0.0000000e+00, -3.1150419e-02,
        -3.8998049e-02,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        -2.1097492e-02,  0.0000000e+00,  0.0000000e+00,  2.5387236e-03,
         3.6670449e-03, -1.5739109e-02,  0.0000000e+00, -2.1528197e-02,
         2.8675018e-02,  3.3587582e-02,  0.0000000e+00,  0.0000000e+00,
        -9.8212494e-04,  1.4884698e-01,  0.0000000e+00, -1.3147130e-02,
        -1.5526453e-02, -1.8523477e-02,  2.6714886e-03, -1.0729245e-02,
        -7.3992200e-03, -1.6481042e-02,  2.9790692e-02, -5.9934799e-03,
        -1.3225219e-01, -2.1428123e-02, -6.6449242e-03, -2.2951167e-02,
        -7.5527276e-03, -8.4643411e-03, -3.0764597e-02, -1.8686436e-02],
       dtype=float32),
 array([[ 4.99498274e-05],
        [-1.93085045e-01],
        [-7.92163331e-03],
        [ 1.85913280e-01],
        [ 9.21363160e-02],
        [-1.14206806e-01],
        [-1.62177999e-02],
        [-1.08456044e-02],
        [ 2.06278577e-01],
        [-4.10514604e-03],
        [ 2.20958576e-01],
        [ 1.67615443e-01],
        [ 2.08863616e-03],
        [ 2.07482621e-01],
        [-2.43282199e-01],
        [-2.89014846e-01],
        [-1.07514849e-02],
        [ 7.92067349e-02],
        [-3.59794199e-02],
        [ 1.27142325e-01],
        [ 3.86443995e-02],
        [ 1.45666510e-01],
        [ 1.90234020e-01],
        [ 2.01491043e-01],
        [ 2.36496687e-01],
        [ 3.80191021e-02],
        [ 4.10247743e-02],
        [ 1.81430176e-01],
        [-2.20749244e-01],
        [ 1.18533343e-01],
        [-1.74647421e-01],
        [-4.47412133e-02],
        [ 2.37547114e-01],
        [-7.36218244e-02],
        [-4.13432717e-03],
        [ 1.13553613e-01],
        [ 1.74639329e-01],
        [-1.58810377e-01],
        [-1.86833605e-01],
        [ 2.33445510e-01],
        [-1.69576257e-01],
        [ 2.95623336e-02],
        [ 4.46626246e-02],
        [-1.39831051e-01],
        [ 1.65928081e-02],
        [ 3.63321267e-02],
        [ 1.04060709e-01],
        [-3.15540843e-02],
        [ 1.24084599e-01],
        [-1.21983131e-02],
        [ 7.99746532e-03],
        [-5.30556999e-02],
        [-2.28795573e-01],
        [ 1.71639919e-01],
        [-1.36074632e-01],
        [-1.38652197e-03],
        [-1.27393141e-01],
        [ 4.84226383e-02],
        [-2.57045358e-01],
        [ 2.34422177e-01],
        [-1.43167034e-01],
        [-1.52703196e-01],
        [ 8.55655372e-02],
        [-1.46831237e-02]], dtype=float32),
 array([0.00553609], dtype=float32)]

In [18]:
# ANN architecvture 

model=Sequential()

# layer1  (input layer )
model.add(Dense(64,activation="relu",input_dim=9))

# layer 2
model.add(Dense(64,activation="relu"))

# output layer
model.add(Dense(1,activation="sigmoid"))

c:\Users\INDIAN\Downloads\Artificaial_NN\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [19]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 64)             │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,865 (19.00 KB)

 Trainable params: 4,865 (19.00 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
# compile 
model.compile(optimizer="Adam",loss="binary_crossentropy",metrics=["accuracy"])

In [25]:
# model fit 
model.fit(x_train,y_train,batch_size=32,epochs=10)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.6744 - loss: 1155.7332
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6890 - loss: 97.0653
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6774 - loss: 124.8930
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6791 - loss: 102.3429
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6789 - loss: 84.0874
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6791 - loss: 81.6162
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6770 - loss: 84.4258
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6839 - loss: 86.2525
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6800 - loss: 69.0439
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6910 - loss: 94.2155